### ISSUE TITLE
关于pcb元件的问题

### ISSUE THREAD

**Issue by RealCaCl2** [bclswl0827/OpenNixie#1]
本人使用 kiCAD 导出了 bom 物料清单，但有些元件在淘宝上搜索不到，能否提供一个购买的渠道？

**Comment by bclswl0827** [comment]
这些是我之前的购买链接，供您参考。

![1](https://github.com/bclswl0827/OpenNixie/assets/24319042/d6be75f0-2651-4596-936b-932d8f402555)
![2](https://github.com/bclswl0827/OpenNixie/assets/24319042/10c52ecc-5a89-4689-8a2c-b3ef04830a71)
![3](https://i.ibb.co/C8GHNry/Screenshot-20240131-091150.png)
![4](https://i.ibb.co/hXYhm5k/Screenshot-20240131-091156.png)
![5](https://i.ibb.co/hyfZMRV/Screenshot-20240131-091205.png)
![6](https://i.ibb.co/X82wQqR/Screenshot-20240131-091210.png)

**Comment by RealCaCl2** [comment]
好的 已经解决了 多谢
